routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// use App\order_product;
// use App\order;
use App\product;
use App\User;
use App\brand;
use App\store;
use App\address;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});
// Route::get('/test', function () {
//       Mail::to('mangallatwal@gmail.com')->send(new TestAmazonSes('It works!'));
// });
Route::get('contact', 'feedbackController@index');
Route::get( 'terms', 'PageController@terms' );
Route::get( 'privacy', 'PageController@privacy' );
Route::resource('/admin/notifications','NotificationController');

Route::get('sendbasicemail','MailController@basic_email');

 Route::get('/admin/feedbacks','FeedbackController@index');
 Route::post('/admin/feedbacks/store','FeedbackController@store');
 Route::get('/admin/feedback/edit','FeedbackController@edit');
 Route::get('/admin/feedback/show/{id}','FeedbackController@show');
 Route::get('/admin/feedbacks/{type?}','FeedbackController@index');
Route::resource('admin/contact/registers', 'ContactController');

//  Public pages
Auth::routes();
Route::get('home/sendemail', 'HomeController@sendemail');

Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
Route::group(['middleware' => 'admin'], function() {
    Route::resource('/admin/users','UserController');
    Route::resource('/admin/users','UserController');
    
    Route::resource('/admin/brands','BrandController');
    Route::resource('/admin/offers','OfferController');
    Route::get('/admin/analytics','AnalyticController@index');
    Route::get('/admin/analytics/{compare}', 'AnalyticController@index');
    Route::resource('/admin/products','ProductController');
    Route::resource('/admin/store/owner','StoreownerController');
    // Route::resource('/admin/store/team','TeamController');
    Route::get('/form','PageController@form');
});
Route::resource('/admin/user/password/change','PasswordController');
Route::resource('/admin/profile','ProfileController');
Route::resource('/admin/stores','StoreController');
Route::resource('/admin/categories','CategoryController');
//cart
Route::get('/admin/store/cart/{id}','OrderController@show');
Route::get('/admin/transactions','OrderController@transactions');
Route::get('/admin/store/cart/add/{id}','OrderController@add');
Route::post('/admin/store/cart/store','OrderController@store');
Route::get('/admin/store/cart/edit/{id}','OrderController@edit');
Route::put('/admin/store/cart/update/{id}','OrderController@update');
Route::get('/admin/store/cart/update/place/{id}','OrderController@place');
Route::delete('/admin/store/cart/delete/{id}','OrderController@destroy');
//Team
Route::get('/admin/store/team/{id}','StoreteamController@show');
Route::get('/admin/store/add/{id}','StoreteamController@add');
Route::post('/admin/store/store','StoreteamController@store');
Route::get('/admin/store/edit/{id}','StoreteamController@edit');
Route::put('/admin/store/update/{id}','StoreteamController@update');
Route::delete('/admin/store/delete/{id}','StoreteamController@destroy');
//Store Product
Route::get('/admin/store/product/{id}','StoreproductController@show');
Route::get('/admin/store/product/add/{id}','StoreproductController@add');
Route::post('/admin/store/product/store','StoreproductController@store');
Route::get('/admin/store/product/edit/{id}','StoreproductController@edit');
Route::put('/admin/store/product/update/{id}','StoreproductController@update');
Route::delete('/admin/store/product/delete/{id}','StoreproductController@destroy');
Route::get('/admin/store/products/edit/{id}','StoreproductController@edit_products');
//Order
Route::get('/admin/orders/','ShippingController@view');
Route::get('/admin/orders/{id}','ShippingController@view');
Route::get('/admin/orders/view/{id}','ShippingController@show');
Route::get('/admin/orders/shipping/view/{id}','ShippingController@show');
Route::get('/admin/orders/create/{id}','ShippingController@create');
Route::get('/admin/orders/billing/{id}','ShippingController@billing');
Route::put('/admin/orders/updatebilling/{id}','ShippingController@billingupdated');
Route::post('/admin/orders/store','ShippingController@store');
Route::delete('/admin/orders/delete/{id}','ShippingController@destroy');

//purchase orders
Route::get('/admin/purchase/orders/{id}','PurchaseOrderController@index');
Route::get('/admin/purchase/order/products/{id}','PurchaseOrderController@create');
Route::post('/admin/purchase/cart/','PurchaseOrderController@add_cart');
Route::get('/admin/purchase/carts/{id}','PurchaseOrderController@carts');
Route::get('/admin/purchase/delete/{id}','PurchaseOrderController@destroy');
Route::post('/admin/purchase/order/store','PurchaseOrderController@store');

Route::get('admin/order/pdf/{id}','OrderController@generatePDF');



Route::get('/admin/stores/{compare}/{id}','StoreController@view');
Route::post('/home', 'HomeController@index');

Route::resource('/admin/supplier','SupplierController');
Route::resource('/admin/employees','EmploEmployeeController');
Route::resource('/admin/clients','ClientController');




Route::get('admin/import', function() {

    $filepath =  url( asset( '/public/data/productss.csv' ) );
    $file = fopen( $filepath, 'r' );
    $importData_arr = array();
    $i = 0;
    while (($filedata = fgetcsv($file, 1000, ",")) !== FALSE) {
        $num = count($filedata );
        // Skip first row (Remove below comment if you want to skip the first row)
        if($i == 0){
            $i++;
            continue;
        }
        for ($c=0; $c < $num; $c++) {
            $importData_arr[$i][] = $filedata [$c];
        }
        $i++;
    }
    fclose($file);

    // Insert to MySQL database
    foreach($importData_arr as $importData){


         $insertData = array(
            'fileID'    => $importData[1],
            'brandID'   => $importData[2],
            'category'  => $importData[4],
            'title'     => $importData[7],
            'pieces'    => $importData[10],
            'brandID'   => $importData[2],
            'box'       => $importData[11],
            'price'     => $importData[12],
            'weight'    => $importData[14],
            'unit'      => $importData[15],
            'hsn'       => $importData[16],
            'tax'       => $importData[17],
            'cess'      => $importData[18],
            'stock'     => $importData[22],
            'status'    => 1,
        );
         if ($importData[13] == 0) {
               $insertData['max_price'] = $importData[12];
            }else{
               $insertData['max_price'] = $importData[13];
            }
        // insert products data

        product::create($insertData);
       

        // Redirect to index
        // print_r($insertData);
    }
    
});
Route::get('admin/orders/insert', function() {
    //  TRUNCATE `orders`;TRUNCATE `order_products`;
    $page = 1;
    if( isset( $_REQUEST['page'] ) && !empty( $_REQUEST['page'] ) ) {
        $page = intval( $_REQUEST['page'] );
    }
    $limit = 2000;
    $offset = ($page - 1) * $limit;

    $ordersJson =  url(asset('/public/data/orders.json'));

    $orders = file_get_contents( $ordersJson, true );
    if( isset( $orders ) && !empty( $orders ) ) {
        $orders = json_decode( $orders, true );
        if( count( $orders ) > $limit ) {
            $orders = array_splice( $orders, $offset, $limit );
        }
        foreach( $orders as $key => $order ) {
            $order['orderID']  = ( $key + 1 );
            $order['products'] = json_encode( $order['products'] );

            //  Generate order
            // $order['orderID'] = DB::table( 'orders' )->insertGetId( $order );

            if( isset( $order['products'] ) && !empty( $order['products'] ) ) {
                $order['products'] = json_decode( $order['products'], true );
                foreach ( $order['products'] as $k => $product ) {
                    // $product['orderID'] = $order['orderID'];
                    // DB::table( 'order_products' )->insertGetId( $product );
                }
            }

            print_r( 'Inserted order #' . $order['orderID'] . PHP_EOL );
        }
    }
    exit;
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

if(!Auth::user())
{
return redirect('/login'); // add your desire URL in redirect function
}

resources/views/admin/add-team.blade.php
@extends('layouts/admin')
@section('title','Add Member') 
@section('content')
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">
            Add a Member
        </h6>
    </div>
    <div class="card-body">
        <form method="post" action="{{ url('/admin/store/store/') }}" >
            @csrf
            <div class="form-row">
                <div class="form-group col-md-6 mx-auto">
                    <label>Mobile No<span class="text-danger">*</span></label>
                    <input type="text" id="txtPhoneNo"  onkeypress="return isNumber(event)" name="mobile" value="{{ old('mobile')}}" placeholder="Enter Mobile Number" maxlength="10"  class="form-control" required="required"> 
                    @error('mobile')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                    @if(session('error'))
                    <strong class="text-danger">{{session('error')}}</strong>
                    @endif
                </div>
            </div>
            <input type="hidden" name="storeID"  value="<?php echo Request::segment(4); ?>">
            <div class="form-group col-md-6 mx-auto">
                <button type="submit" class="btn btn-success" onclick="ValidateNo();">
                    <i class="bi bi-file-earmark-plus"></i><span class="pl-2">Add</span>
                </button>
                <a class="btn btn-outline-secondary" href="{{ url('/admin/store/team/'.Request::segment(4)) }}" role="button" title="Go back">
                    <i class="bi bi-caret-left"></i>
                    <span>Back</span>
                </a>
                <a href="{{ route('users.create')}}"><strong>Create User</strong></a>
            </form>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">
    function isNumber(evt) {
          evt = (evt) ? evt : window.event;
          var charCode = (evt.which) ? evt.which : evt.keyCode;
          if (charCode > 31 && (charCode < 48 || charCode > 57)) {
            alert("Please enter only Numbers.");
            return false;
          }

          return true;
    }

    function ValidateNo() {
          var phoneNo = document.getElementById('txtPhoneNo');

          if (phoneNo.value == "" || phoneNo.value == null) {
            alert("Please enter your Mobile No.");
            return false;
          }
          if (phoneNo.value.length < 10 || phoneNo.value.length > 10) {
            alert("Mobile No. is not valid, Please Enter 10 Digit Mobile No.");
            return false;
          }

          // alert("Success ");
          // return true;
    }
</script>
@endsection

resources/views/admin/addStore.blade.php
@extends('layouts/admin')

@section('title','store page')

@section('content')
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Create Store </h6>
      </div>
     <div class="card-body">
		<form method="post" action="{{ route('stores.store') }}" enctype="multipart/form-data" >
       @csrf
  <div class="form-row">
    <div class="form-group col-md-6">
      <label >Users</label>
      <select id="inputState" class="form-control" name="Users">
        <option>---Select user---</option>
         @foreach($user as $value)
        <option value="{{ $value->id }}" >{{ $value->name }}</option>
      
        @endforeach
      </select>
    </div>
    <div class="form-group col-md-6"> 
      <label>title </label>
      <input type="text" class="form-control"  name="title">
      @error('title')
      <span class="feedback" role="alert">
      <strong class="text-danger">{{ $message }}</strong>
      </span>
      @enderror
    </div>
</div>
  <div class="form-row">
   <div class="form-group col-md-6">
      <label>slug </label>
      <input type="text" class="form-control"   name="slug">
       @error('slug')
      <span class="feedback" role="alert">
      <strong class="text-danger">{{ $message }}</strong>
      </span>
      @enderror
    </div>
   <div class="form-group col-md-3">
      <label>tagline </label>
      <input type="text" class="form-control"  name="tagline">
       @error('tagline')
      <span class="feedback" role="alert">
      <strong class="text-danger">{{ $message }}</strong>
      </span>
      @enderror
    </div>
     <div class="form-group col-md-3">
      <label>keyword </label>
      <input type="text" class="form-control"  name="keyword">
       @error('keyword')
      <span class="feedback" role="alert">
      <strong class="text-danger">{{ $message }}</strong>
      </span>
      @enderror
    </div>
</div>

  <div class="form-row">
     <div class="form-group col-md-6">
      <label>domain </label>
      <input type="text" class="form-control"  name="domain">
       @error('domain')
      <span class="feedback" role="alert">
      <strong class="text-danger">{{ $message }}</strong>
      </span>
      @enderror
    </div>
   <div class="form-group col-md-6">
      <label>favicon </label>
      <input type="text" class="form-control"  name="favicon">
       @error('favicon')
      <span class="feedback" role="alert">
      <strong class="text-danger">{{ $message }}</strong>
      </span>
      @enderror
    </div>
</div>

 <div class="form-row">
     <div class="form-group col-md-6">
    <label>description</label>
    <textarea class="form-control"   name="description"></textarea> 
      @error('description')
      <span class="feedback" role="alert">
      <strong class="text-danger">{{ $message }}</strong>
      </span>
      @enderror
    </div>
    <div class="form-group col-md-6">
      <label >Future Pictures</label>
     <input type="file" name="fileToUpload" class="form-control">
      @error('fileToUpload')
      <span class="feedback" role="alert">
      <strong class="text-danger">{{ $message }}</strong>
      </span>
      @enderror
    </div>
  </div>
<button type="submit" class="btn btn-primary">ADD STORE</button>
</form>
</div>
</div>
@endsection

resources/views/admin/clients.blade.php
@extends('layouts/admin')

@section('title','Clients')

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header">
            <div class="row align-items-center">
                <div class="col-md-6">
                    <h6 class="m-0 font-weight-bold text-primary">Clients</h6>
                </div>
                <div class="col-md-6 text-right">
                    
                </div>
            </div>
        </div>

        @if ($message = Session::get('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <span>{{ $message }}</span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        @endif

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm table-striped table-bordered table-hover" width="100%" cellspacing="0" id="myTable">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Mobile</th>
                            <th scope="col">Company</th>
                         <!--    <th scope="col">Stores</th> -->
                            <th scope="col">Joined</th>
                            <!-- <th>Action</th> -->
                        </tr>
                    </thead>
                    
                    <tbody>
                        @foreach($data as $value)
                        <tr>
                            <td scope="row">{{ $value->userID }}</td>
                            <td>
                                <!-- <a href="{{ route('users.show', $value->userID ) }}"> -->
                                   <?php if($value->fileID > 0){ ?>
                                    <img class="img-fluid" src="{{ asset('public/uploads/'.$value->uri )}}" height="32" width="auto" style="height: 2rem;">
                                <?php }else{ ?>
                                          <img class="img-fluid" src="{{ asset('public/uploads/user.jpg')}}" height="32" width="auto" style="height: 2rem;">
                               <?php  } ?>
                                <!-- </a> -->
                                <?php echo ucfirst($value->name); ?>
                            </td>
                            <td>{{ $value->email }}</td>
                            <td>+{{ $value->countryPhoneCode }}-{{ $value->mobile }}</td>
                            <td>{{ $value->company }}</td>
                            <!-- <td>{{ $value->stores ?? 0 }}</td> -->
                            <td><?php echo  date('d M Y',strtotime($value->created)); ?></td>
                                <!-- <td>

                                 <a href="{{ route('change.edit', $value->userID )}}" class="btn btn-success">Change Password</i></a>
                             </td> -->

                            <!-- <td>
                                <form action="{{ route('users.destroy', $value->userID ) }}" method="post">

                                    <a href="{{ route('users.show', $value->userID )}}" class="btn btn-info"><i class="fa fa-eye" ></i></a>

                                    <a href="{{ route('users.edit', $value->userID )}}" class="btn btn-success"><i class="fa fa-edit" ></i></a>

                                    <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                    @csrf @method('DELETE')

                                </form>
                            </td> -->
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div><!-- /.table-responsive -->
        </div><!-- /.card-body -->
    </div><!-- /.card -->
@endsection
@section('stylesheets')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
@endsection

@section('scripts')
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
    $(document).ready( function () {
        $('#myTable').DataTable({
          'order' : [],
          "pageLength": 25
        });
    });
</script>
@endsection

resources/views/admin/contacts.blade.php
@extends('layouts/admin')

@section('title','Feedbacks')

@section('content')
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Contact Registers</h6>
    </div>
    @if ($message = Session::get('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <span>{{ $message }}</span>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    @endif
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-sm table-striped table-bordered table-hover" width="100%" cellspacing="0" id="myTable">
                <thead class="thead-dark">
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Mobile</th>
                        <th>Subject</th>
                        <th>Message</th>
                        <th>Created</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="active">
                        @foreach($data as $value)
                        <td>{{++$i}}</td>
                        <td>{{ $value->name }}</td>
                        <td><a  href="{{ route('registers.show',$value->feedbackID) }}" >{{ $value->email}}</a></td>
                        <td>{{ $value->mobile }}</td>
                        <td>{{ $value->subject}}</td>
                        <td>{{ $value->message}}</td>
                        <td><?php echo  date('d M Y',strtotime($value->created)); ?></td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
@section('stylesheets')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
@endsection

@section('scripts')
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
    $(document).ready( function () {
        $('#myTable').DataTable({
          'order' : [],
          "pageLength": 25
        });
    });
</script>
@endsection

resources/views/admin/profile.blade.php
@extends('layouts/admin')

@section('title','Profile-'.$data->name)

@section('content')
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Profile</h6>
    </div>
    <div class="row">
        <div class="col-md-4">
            <?php if($data->fileID > 0){?>
                <img class="card-img-bottom" src="{{ asset('public/uploads/'.$file->uri)}}"  width="100%" >
            <?php }else{ ?>
                <img class="card-img-bottom" src="{{ asset('public/uploads/user.jpg')}}" width="auto" >
            <?php } ?>
            <table cellpadding="10">
                <?php if(Auth::check() && Auth::User()->role ==1 ){ ?>
                    <tr>
                        <td>
                            <a href="{{ route('users.edit', $data->userID ) }}" class="btn btn-primary">
                                <i class="bi bi-pencil-square"></i>
                                <span>Edit</span>
                            </a>
                        </td>
                        <td style="text-align: right;">
                            <a class="btn btn-outline-secondary" href="{{ url('/admin/employees') }}" role="button" title="Go back">
                                <i class="bi bi-caret-left"></i>
                                <span>Back</span>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <a href="{{ route('change.edit', $data->userID )}}" class="btn btn-info">
                               <i class="bi bi-key"></i> <span> Change Password </span>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
        </div>
        <div class="col-md-4">
            <table cellpadding="10">
                <tbody>
                    <tr>
                        <td><strong>Name :</strong></td>
                        <td>{{ $data->name}}</td>
                    </tr>
                    <tr>
                        <td><strong>Email :</strong></td>
                        <td> {{$data->email}}</td>
                    </tr>
                    <tr>
                        <td> <strong>Phone :</strong></td>
                        <td> {{$data->mobile}}</td>
                    </tr>
                    <tr>
                        <td><strong>DOB:</strong></td>
                        <td> {{$data->dob}}</td>
                    </tr>
                    <tr>
                        <td><strong>Company:</strong></td>
                        <td> {{$data->company}}</td>
                    </tr>
                    <tr>
                        <td><strong>Position:</strong> </td>
                        <td>{{$data->position}}</td>
                    </tr>
                    <tr>
                        <td> <strong>Website:</strong></td>
                        <td> {{$data->website}}</td>
                    </tr>
                    <tr>
                        <td><strong>No of  Order  Placed :</strong></td>
                        <td>{{ $order}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-4">
             <table class="table table-bordered">
                <tr>
                    <th>StoreID</th>
                    <th>Role</th>
                </tr>
                <?php $i = 0; ?>
                @foreach($store as $value)
                <tr>
                    <td>{{ $value->storeID }}</td>
                    <td><?php if ($value->storeID == 1) {
                      echo 'admin';
                    }else{
                      echo 'Manager';
                    } ?></td>
                    @endforeach
                </tr>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/admin/teams.blade.php
@extends('layouts/admin')

@section('title','Team Member page')

@section('content')
<div class="card shadow mb-4">
        <div class="card-header">
            <div class="row align-items-center">
                <div class="col-md-6">
                    <h6 class="m-0 font-weight-bold text-primary">Teams </h6>
                </div>
                <div class="col-md-6 text-right">
                    <a href="{{ url('/admin/store/add/'.Request::segment(4).'/') }}" class="btn btn-primary">+ADD TEAM MEMBER</a>
                </div>
            </div>
        </div>

        @if ($message = Session::get('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <span>{{ $message }}</span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        @endif

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm table-striped table-bordered table-hover" width="100%" cellspacing="0" id="myTable">
                    <thead class="thead-dark">
                        <tr>
                            <th>#</th>
                            <th>User Name</th>
                            <th>Role</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($data as $value )
                        <tr> 
                            <td scope="row">#{{ $value->teamID }}</td>
                            <td>
                                <?php if($value->userID == $value->owner ){ ?>
                                    {{ $value->name}}
                                <?php }else{ ?>
                                    <a href="{{ url('/admin/store/edit/'.$value->teamID.'/') }}">{{ $value->name}}</a>
                                <?php } ?>
                            </td>
                             <td><?php if($value->userID == $value->owner && $value->role == 1){
                                echo "Owner";
                            }elseif ($value->role == 2 ) {
                                 echo "Manager";
                            }elseif ($value->role == 3 ) {
                                echo "Customer";
                            }elseif ($value->role == 1) {
                                echo "Admin";
                            }else{
                                echo "Employee";
                            } ?></td>
                           
                         </tr>
                    @endforeach
                    </tbody>
                </table>
            </div><!-- /.table-responsive -->
        </div><!-- /.card-body -->
    </div><!-- /.card -->
@endsection
@section('stylesheets')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
@endsection

@section('scripts')
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
    $(document).ready( function () {
        $('#myTable').DataTable({
          'order' : []
        });
    });
</script>
@endsection
    

resources/views/admin/viewContact.blade.php
@extends('layouts/admin')

@section('title','Feedback page')

@section('content')
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Feedback</h6>
    </div>
    <div class="card-body">
        <div class="form-row">
            <div class="form-group col-md-4 mx-auto">
                <table>
             		<tr>
             			<td><strong>Name: </strong></td><td>{{ $data->name}}</td>
             		</tr>
             		<tr>
             			<td><strong>Email: </strong></td><td>{{$data->email}}</td>
             		</tr>
                    <tr>
                        <td><strong>Mobile: </strong></td><td>{{$data->mobile}}</td>
                    </tr>
                    <tr>
                        <td><strong>Store Name: </strong></td><td>{{$data->company_name}}</td>
                    </tr>
             		<tr>
             			<td><strong>Subject:</strong></td><td>{{$data->subject}}</td>
             		</tr>
             		<tr>
             			<td><strong>Message:</strong></td><td>{{$data->message}}</td>
             		</tr>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection