routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// use App\order_product;
// use App\order;
use App\product;
use App\User;
use App\brand;
use App\store;
use App\address;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});
// Route::get('/test', function () {
//       Mail::to('mangallatwal@gmail.com')->send(new TestAmazonSes('It works!'));
// });
Route::get('contact', 'feedbackController@index');
Route::get( 'terms', 'PageController@terms' );
Route::get( 'privacy', 'PageController@privacy' );
Route::resource('/admin/notifications','NotificationController');

Route::get('sendbasicemail','MailController@basic_email');

 Route::get('/admin/feedbacks','FeedbackController@index');
 Route::post('/admin/feedbacks/store','FeedbackController@store');
 Route::get('/admin/feedback/edit','FeedbackController@edit');
 Route::get('/admin/feedback/show/{id}','FeedbackController@show');
 Route::get('/admin/feedbacks/{type?}','FeedbackController@index');
Route::resource('admin/contact/registers', 'ContactController');

//  Public pages
Auth::routes();
Route::get('home/sendemail', 'HomeController@sendemail');

Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
Route::group(['middleware' => 'admin'], function() {
    Route::resource('/admin/users','UserController');
    Route::resource('/admin/users','UserController');
    
    Route::resource('/admin/brands','BrandController');
    Route::resource('/admin/offers','OfferController');
    Route::get('/admin/analytics','AnalyticController@index');
    Route::get('/admin/analytics/{compare}', 'AnalyticController@index');
    Route::resource('/admin/products','ProductController');
    Route::resource('/admin/store/owner','StoreownerController');
    // Route::resource('/admin/store/team','TeamController');
    Route::get('/form','PageController@form');
});
Route::resource('/admin/user/password/change','PasswordController');
Route::resource('/admin/profile','ProfileController');
Route::resource('/admin/stores','StoreController');
Route::resource('/admin/categories','CategoryController');
//cart
Route::get('/admin/store/cart/{id}','OrderController@show');
Route::get('/admin/transactions','OrderController@transactions');
Route::get('/admin/store/cart/add/{id}','OrderController@add');
Route::post('/admin/store/cart/store','OrderController@store');
Route::get('/admin/store/cart/edit/{id}','OrderController@edit');
Route::put('/admin/store/cart/update/{id}','OrderController@update');
Route::get('/admin/store/cart/update/place/{id}','OrderController@place');
Route::delete('/admin/store/cart/delete/{id}','OrderController@destroy');
//Team
Route::get('/admin/store/team/{id}','StoreteamController@show');
Route::get('/admin/store/add/{id}','StoreteamController@add');
Route::post('/admin/store/store','StoreteamController@store');
Route::get('/admin/store/edit/{id}','StoreteamController@edit');
Route::put('/admin/store/update/{id}','StoreteamController@update');
Route::delete('/admin/store/delete/{id}','StoreteamController@destroy');
//Store Product
Route::get('/admin/store/product/{id}','StoreproductController@show');
Route::get('/admin/store/product/add/{id}','StoreproductController@add');
Route::post('/admin/store/product/store','StoreproductController@store');
Route::get('/admin/store/product/edit/{id}','StoreproductController@edit');
Route::put('/admin/store/product/update/{id}','StoreproductController@update');
Route::delete('/admin/store/product/delete/{id}','StoreproductController@destroy');
Route::get('/admin/store/products/edit/{id}','StoreproductController@edit_products');
//Order
Route::get('/admin/orders/','ShippingController@view');
Route::get('/admin/orders/{id}','ShippingController@view');
Route::get('/admin/orders/view/{id}','ShippingController@show');
Route::get('/admin/orders/shipping/view/{id}','ShippingController@show');
Route::get('/admin/orders/create/{id}','ShippingController@create');
Route::get('/admin/orders/billing/{id}','ShippingController@billing');
Route::put('/admin/orders/updatebilling/{id}','ShippingController@billingupdated');
Route::post('/admin/orders/store','ShippingController@store');
Route::delete('/admin/orders/delete/{id}','ShippingController@destroy');

//purchase orders
Route::get('/admin/purchase/orders/{id}','PurchaseOrderController@index');
Route::get('/admin/purchase/order/products/{id}','PurchaseOrderController@create');
Route::post('/admin/purchase/cart/','PurchaseOrderController@add_cart');
Route::get('/admin/purchase/carts/{id}','PurchaseOrderController@carts');
Route::get('/admin/purchase/delete/{id}','PurchaseOrderController@destroy');
Route::post('/admin/purchase/order/store','PurchaseOrderController@store');

Route::get('admin/order/pdf/{id}','OrderController@generatePDF');



Route::get('/admin/stores/{compare}/{id}','StoreController@view');
Route::post('/home', 'HomeController@index');

Route::resource('/admin/supplier','SupplierController');
Route::resource('/admin/employees','EmploEmployeeController');
Route::resource('/admin/clients','ClientController');




Route::get('admin/import', function() {

    $filepath =  url( asset( '/public/data/productss.csv' ) );
    $file = fopen( $filepath, 'r' );
    $importData_arr = array();
    $i = 0;
    while (($filedata = fgetcsv($file, 1000, ",")) !== FALSE) {
        $num = count($filedata );
        // Skip first row (Remove below comment if you want to skip the first row)
        if($i == 0){
            $i++;
            continue;
        }
        for ($c=0; $c < $num; $c++) {
            $importData_arr[$i][] = $filedata [$c];
        }
        $i++;
    }
    fclose($file);

    // Insert to MySQL database
    foreach($importData_arr as $importData){


         $insertData = array(
            'fileID'    => $importData[1],
            'brandID'   => $importData[2],
            'category'  => $importData[4],
            'title'     => $importData[7],
            'pieces'    => $importData[10],
            'brandID'   => $importData[2],
            'box'       => $importData[11],
            'price'     => $importData[12],
            'weight'    => $importData[14],
            'unit'      => $importData[15],
            'hsn'       => $importData[16],
            'tax'       => $importData[17],
            'cess'      => $importData[18],
            'stock'     => $importData[22],
            'status'    => 1,
        );
         if ($importData[13] == 0) {
               $insertData['max_price'] = $importData[12];
            }else{
               $insertData['max_price'] = $importData[13];
            }
        // insert products data

        product::create($insertData);
       

        // Redirect to index
        // print_r($insertData);
    }
    
});
Route::get('admin/orders/insert', function() {
    //  TRUNCATE `orders`;TRUNCATE `order_products`;
    $page = 1;
    if( isset( $_REQUEST['page'] ) && !empty( $_REQUEST['page'] ) ) {
        $page = intval( $_REQUEST['page'] );
    }
    $limit = 2000;
    $offset = ($page - 1) * $limit;

    $ordersJson =  url(asset('/public/data/orders.json'));

    $orders = file_get_contents( $ordersJson, true );
    if( isset( $orders ) && !empty( $orders ) ) {
        $orders = json_decode( $orders, true );
        if( count( $orders ) > $limit ) {
            $orders = array_splice( $orders, $offset, $limit );
        }
        foreach( $orders as $key => $order ) {
            $order['orderID']  = ( $key + 1 );
            $order['products'] = json_encode( $order['products'] );

            //  Generate order
            // $order['orderID'] = DB::table( 'orders' )->insertGetId( $order );

            if( isset( $order['products'] ) && !empty( $order['products'] ) ) {
                $order['products'] = json_decode( $order['products'], true );
                foreach ( $order['products'] as $k => $product ) {
                    // $product['orderID'] = $order['orderID'];
                    // DB::table( 'order_products' )->insertGetId( $product );
                }
            }

            print_r( 'Inserted order #' . $order['orderID'] . PHP_EOL );
        }
    }
    exit;
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

if(!Auth::user())
{
return redirect('/login'); // add your desire URL in redirect function
}

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@yield('title') | {{ config('app.name', 'SupplyPort') }}</title>

    <link rel="stylesheet" href="{{ asset('public/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('public/css/bootstrap-icons.css') }}">
    <link rel="stylesheet" href="{{ asset('public/css/admin.css') }}">
    <!-- <link rel="stylesheet" href="{{ asset('public/css/all.min.css') }}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" /> -->
    <link rel="shortcut icon" href="./favicon.ico" type="image/x-icon">
    <link rel="icon" href="./favicon.ico" type="image/x-icon">
    @yield('stylesheets')
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top flex-md-nowrap p-0">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{{ route('home') }}" title="{{ config('app.name','SupplyPort') }}">
            <!-- <div class=""> -->
            <?php print file_get_contents( asset('public/media/icon-logo-1.svg') );?>
            <!-- </div> -->
        </a>
        
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="profileDropDown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ Auth::user()->name }} <span class="caret"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="profileDropDown">
                   <a class="dropdown-item" href="{{ route('profile.show',Auth::user()->userID)}}">
                        <i class="bi bi-person"></i>
                        <span>Profile</span>
                    </a>
                    <a class="dropdown-item" href="{{ route('change.edit',Auth::user()->userID ) }}" >
                        <i class="bi bi-key"></i>
                        <span>Change Password</span>
                    </a>
                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        <i class="bi bi-unlock"></i>
                        <span>{{ __('Logout') }}</span>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </a>
                </div>
            </li>
        </ul>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <aside id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="sidebar-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link{{ (request()->is('home')) ? ' active' : '' }}" href="{{url('home') }}">
                                <i class="bi bi-house-door"></i>
                                <span>Home</span>
                            </a>
                        </li>
                        
                        @if( Auth::user()->role == 1 )
                        <li class="nav-item">
                            <a class="nav-link{{ (request()->is('admin/orders*')) ? ' active' : '' }}" href="{{ url('/admin/orders')}}">
                                <i class="bi bi-cart4"></i>
                                <span>Orders</span>
                            </a>
                        </li>
                        @endif
                        
                        @if( in_array( Auth::user()->role, array( 1, 2, 3 ) ) )
                            <!-- <li class="nav-item">
                                <a class="nav-link{{ (request()->is('admin/purchase/orders*')) ? ' active' : '' }}" href="{{ url('admin/purchase/orders') }}">
                                    <i class="bi bi-bag"></i>
                                    <span>Purchase Orders</span>
                                </a>
                            </li>  --> 
                            <li class="nav-item">
                                <a class="nav-link{{ (request()->is('admin/stores*')) ? ' active' : '' }}" href="{{ url('/admin/stores') }}">
                                    <i class="bi bi-shop"></i>
                                    <span>Stores</span>
                                </a>
                            </li>                         
                        @endif

                        @if( Auth::user()->role == 1 )
                        <li class="nav-item">
                            <a class="nav-link{{ (request()->is('admin/clients*')) ? ' active' : '' }}" href="{{ url('/admin/clients') }}">
                                <i class="bi bi-person"></i>
                                <span>Clients</span>
                            </a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link{{ (request()->is('admin/transactions*')) ? ' active' : '' }}" href="{{ url('/admin/transactions') }}">
                                <i class="bi bi-wallet"></i>
                                <span>Transactions</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link{{ (request()->is('admin/employees*')) ? ' active' : '' }}" href="{{ url('/admin/employees') }}">
                                <i class="bi bi-person-bounding-box"></i>
                                <span>Employees</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link{{ (request()->is('admin/supplier*')) ? ' active' : '' }}" href="{{ url('/admin/supplier') }}">
                                <i class="bi bi-truck"></i>
                                <span>Suppliers</span>
                            </a>
                        </li>  
                        <li class="nav-item">
                            <a class="nav-link{{ (request()->is('admin/analytics')) ? ' active' : '' }}" href="{{url('admin/analytics') }}">
                                <i class="bi bi-bar-chart"></i>
                                <span>Analytics</span>
                            </a>
                        </li>
                         
                        <li class="nav-item">
                            <a class="nav-link{{ (request()->is('admin/products*')) ? ' active' : '' }}" href="{{ url('/admin/products') }}">
                                <i class="bi bi-box-seam"></i>
                                <span>Products</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link{{ (request()->is('admin/brands*')) ? ' active' : '' }}" href="{{ url('/admin/brands')}}">
                                <i class="bi bi-puzzle"></i>
                                <span>Brands</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link{{ (request()->is('admin/categories*')) ? ' active' : '' }}" href="{{ url('/admin/categories')}}">
                                <i class="bi bi-tags"></i>
                                <span>Categories</span>
                            </a>
                        </li>
                        @endif
                        
                        @if( in_array( Auth::user()->role, array( 1, 2, 3 ) ) )
                         <li class="nav-item">
                            <a class="nav-link{{ (request()->is('/admin/notifications*')) ? ' active' : '' }}" href="{{ url('/admin/notifications') }}">
                                <i class="bi bi-bell"></i>
                                <span>Notifications</span>
                            </a>
                        </li>
                       
                        @endif
                        @if( Auth::user()->role == 1 )
                        <li class="nav-item">
                            <a class="nav-link{{ (request()->is('admin/users*')) ? ' active' : '' }}" href="{{ url('/admin/users') }}">
                                <i class="bi bi-people"></i>
                                <span>Users</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link{{ (request()->is('admin/offers*')) ? ' active' : '' }}" href="{{ url('/admin/offers')}}">
                                <i class="bi bi-tag"></i>
                                <span>Offers</span>
                            </a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link{{ (request()->is('admin/feedbacks*')) ? ' active' : '' }}" href="{{ url('/admin/feedbacks') }}">
                                <i class="bi bi-mailbox"></i>
                                <span>Feedback</span>
                            </a>
                        </li>   
                         <li class="nav-item">
                            <a class="nav-link{{ (request()->is('admin/contact/registers*')) ? ' active' : '' }}" href="{{ url('/admin/contact/registers') }}">
                                <i class="bi bi-receipt"></i>
                                <span>Contact Registers</span>
                            </a>
                        </li>                         
                        @endif                      
                     </ul>
                </div>
            </aside>
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                 @yield('content')
            </main>
        </div>
    </div>

    <script src="{{ asset('public/js/jquery.slim.min.js') }}"></script>
    <script src="{{ asset('public/js/bootstrap.bundle.min.js') }}"></script>
    <!-- <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script> -->
    <!-- <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script> -->
    <!-- <script>feather.replace();</script> -->
    <?php if( request()->is('analytics') ) :?>
         <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <?php endif;?>
    @yield('scripts')
</body>
</html>